### ISSUE TITLE
Feature request : native windows builds - msvc compiler support

### ISSUE THREAD

**Issue by solvingj** [octaspire/core#1]
I was excited to read about this library but was surprised and disappointed that the supported build system is not a cross-platform meta-build system. I understand why people like gnu make, but it’s a barrier to a better cross platform ecosystem of OSS libraries.  Since the makefile is very skillfully written, this ticket seems likely to be closed as won’t do, but I wanted to ask because your projects are interesting.

**Comment by octaspire** [comment]
Thank you for the feature request :-) 

I added support for MSVC C/C++ compiler in commit 85268527a5217d3281298baca4a7847998cd3439

I tested it with 'Visual Studio 2017 (Community edition)'

Usage:

1. Download and install required tools from the internet:

````
'Visual Studio 2017 (Community edition)'
'git'
````

2. Start 'Developer Command Prompt for VS 2017'.
    It can be found under 'Visual Studio 2017' in
    the start menu.

    Please note, that you cannot use regular windows
    command prompt.

3. Change to a directory you want to use. For example:

````sh
         cd c:\
````

4. Clone the development repository using git:

````sh
         git clone https://github.com/octaspire/core.git
````

5. Change into the correct directory for using 'Core':

````sh
         cd core\release
````

6. Build unit test runner and an example program with command:

````sh
         how-to-build\windows-msvc.bat
````

You should now have two executable programs
(unit test runner and an example program) and
also instructions for building those programs.

Please note, that the recommended way of using
Core is to use the amalgamation. It is just
one source file that contains **everything**.

So hopefully there should be no need for any
build tool (like *make*, *gmake*, *nmake* or *ninja*)
or metabuild tool (like *CMake*).

**Make** is used only as a helper when developing Core itself.
**CMake** was used before, but I replaced it with plain handwritten
Makefile to streamline things and get rid of additional tool dependency.
But again, I hope that Core could be used without any build tools (or easily with any build tool or project) just by dropping the amalgamation
(release/octaspire-core-amalgamated.c) into place and
maybe adding one or two -Dxyz definitions.  

Hopefully commit  85268527a5217d3281298baca4a7847998cd3439 is useful. Please feel free to comment, if something doesn't work or make sense, or if you have some specific cross platform usage barrier. I have tried to make Core and Dern very cross platform, and have been running them for example in  Amiga, AROS, Haiku, Plan9, Syllable desktop, many different Unixes (minix, macOS, FreeBSD, OpenBSD, DragonFlyBSD, MidnightBSD, NetBSD, OpenIndiana), React OS and Windows. I hope that they could be used without the need for any build tools (or easily with any).

**Comment by octaspire** [comment]
I hope that this feature request is now implemented OK and will thus close this issue. Please (re)open an issue if needed. 

P.S. I am also implementing this same feature request for Dern. Some of the examples, programs and plugins are already built with Microsoft Visual Studio C/C++ in Windows using 'how-to-build'-script in `release/how-to-build/windows-msvc.bat`.
